# Generated by Django 5.2.16 on 2026-07-12 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TMDBMovieCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tmdb_cache', to='catalog.movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TMDBShowCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tmdb_cache', to='catalog.show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TVmazeShowCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
                ('show', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tvmaze_cache', to='catalog.show')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
