# Generated by Django 5.2.16 on 2026-07-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_episode_primary_title_and_alternates'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='airstamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='alternateepisodetitle',
            constraint=models.UniqueConstraint(fields=('episode', 'title', 'language', 'country'), name='unique_alternate_episode_title'),
        ),
        migrations.AddConstraint(
            model_name='alternatemovietitle',
            constraint=models.UniqueConstraint(fields=('movie', 'title', 'language', 'country'), name='unique_alternate_movie_title'),
        ),
        migrations.AddConstraint(
            model_name='alternateshowtitle',
            constraint=models.UniqueConstraint(fields=('show', 'title', 'language', 'country'), name='unique_alternate_show_title'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('tmdb_id__isnull', False)), name='movie_has_provider_id'),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.CheckConstraint(condition=models.Q(('tvmaze_id__isnull', False), ('tmdb_id__isnull', False), _connector='OR'), name='show_has_provider_id'),
        ),
    ]
