# Generated by Django 5.2.16 on 2026-07-12 06:50

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_episode_airstamp_and_more'),
    ]

    operations = [
        # Fuzzy/typo-tolerant search support (spec §4.6). Requires the DB
        # role to be able to CREATE EXTENSION (true for the compose setup;
        # managed PaaS Postgres add-ons generally allow pg_trgm too).
        TrigramExtension(),
        migrations.AddIndex(
            model_name='alternatemovietitle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='alt_movie_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='alternateshowtitle',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='alt_show_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=django.contrib.postgres.indexes.GinIndex(fields=['primary_title'], name='movie_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='show',
            index=django.contrib.postgres.indexes.GinIndex(fields=['primary_title'], name='show_title_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
