# Generated by Django 5.2.16 on 2026-07-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_syncstate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alternateepisodetitle',
            name='unique_alternate_episode_title',
        ),
        migrations.RemoveConstraint(
            model_name='alternatemovietitle',
            name='unique_alternate_movie_title',
        ),
        migrations.RemoveConstraint(
            model_name='alternateshowtitle',
            name='unique_alternate_show_title',
        ),
        migrations.RemoveField(
            model_name='alternateepisodetitle',
            name='language',
        ),
        migrations.RemoveField(
            model_name='alternatemovietitle',
            name='language',
        ),
        migrations.RemoveField(
            model_name='alternateshowtitle',
            name='language',
        ),
        migrations.AddConstraint(
            model_name='alternateepisodetitle',
            constraint=models.UniqueConstraint(fields=('episode', 'title', 'country'), name='unique_alternate_episode_title'),
        ),
        migrations.AddConstraint(
            model_name='alternatemovietitle',
            constraint=models.UniqueConstraint(fields=('movie', 'title', 'country'), name='unique_alternate_movie_title'),
        ),
        migrations.AddConstraint(
            model_name='alternateshowtitle',
            constraint=models.UniqueConstraint(fields=('show', 'title', 'country'), name='unique_alternate_show_title'),
        ),
    ]
