# Generated by Django 5.2.16 on 2026-07-14 23:07

from django.db import migrations, models


def backfill_is_detail(apps, schema_editor):
    """
    Snapshots written before this flag existed used the presence of the
    "runtime" key to distinguish full /movie/{id} records from partial
    search hits — reuse that here, one last time, to seed the flag.
    """
    TMDBMovieCache = apps.get_model("catalog", "TMDBMovieCache")
    TMDBMovieCache.objects.filter(data__has_key="runtime").update(is_detail=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_alternateepisodetitle_unique_alternate_episode_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmdbmoviecache',
            name='is_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_is_detail, migrations.RunPython.noop),
    ]
