# Generated by Django 5.2.16 on 2026-07-12 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('app_trial', 'App Trial'), ('google_play', 'Google Play'), ('apple_app_store', 'Apple App Store'), ('admin_grant', 'Admin Grant'), ('tester_grant', 'Tester Grant')], max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('app_trial', 'App Trial'), ('google_play', 'Google Play'), ('apple_app_store', 'Apple App Store'), ('admin_grant', 'Admin Grant'), ('tester_grant', 'Tester Grant')], max_length=20)),
                ('state', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('grace_period', 'Grace Period'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('indefinite', 'Indefinite')], max_length=20)),
                ('google_purchase_token', models.TextField(blank=True, null=True)),
                ('apple_original_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
