# Generated by Django 5.2.16 on 2026-07-12 03:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchedepisode',
            name='watched',
        ),
        migrations.RemoveField(
            model_name='watchedmovie',
            name='watched',
        ),
        migrations.AlterField(
            model_name='watchedepisode',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='watchedmovie',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
