# Generated by Django 5.2.16 on 2026-07-12 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_watchedepisode_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='showsubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10),
        ),
    ]
